### ISSUE TITLE
dataTransforms: Add function to center data

### ISSUE THREAD

**Issue by lizzthabet** [mime-dream-team/whiteboard-model-test#8]
The function will take the raw, filtered data and map all points to a center point. This function will help establish relationships between x and y coordinates.

**Comment by lizzthabet** [comment]
I have a few questions/thoughts and am writing them here so I don't forget: 
*  Because the reorganization of the model `dataTransforms` and `shape`files is a significant amount of work, I think we should create a separate ticket for it. (And then when it's done, we can check an item off our list!)
*  Where or how is the `removeSimilarDataPoints` function being called in the flow of data processing?
*  If not having data to work with on is a blocker for this ticket, I can pull some real fake data from an earlier commit in the repo.

**Comment by cofuente** [comment]
1-sounds good to me!
2-it's called in the processTrainingData function
3-that sounds really good, it would help tons!

**Comment by cofuente** [comment]
whoops, closed by accident. just reopened it.
